**(1)** Given a rotated array of integers, implement a Python program that finds an
    element using binary search. As an example of a rotated array
    A = {4, 5, 6, 1, 2, 3}, index of element 2 is 4. Submit both the Python code
    and a screenshot of its results. <br>
    
*Tip: You will first need to find the cutline, i.e. index of an element which
         is index 0 in the original sorted array. The cutline of A is 3.*

In [1]:
import numpy as np

**[Ric wrote]:** Given that the list may be rotated at any point and that the rotated list is neither in ascending or descending order, I will use lianear search to find the cutline index. In this case the cutline would be the integer with the smaller value.

In [174]:
def findCutline(arr):
    """Input: A rotated array
    Output: the index of the cutline"""
    
    if isinstance(arr,list) or isinstance(arr,tuple):
        array = np.array(arr)
    elif isinstance(a,np.ndarray):
        array = np.copy(arr)
    else:
        raise ValueError("The input has to be either numpy array, list, or tuple")
    
    minVal = array[0]
    cutlineIndex = 0
    
    for indx,val in enumerate(arr):
        if val < minVal:
            minVal = val
            cutlineIndex = indx
    
    return cutlineIndex

In [175]:
a = np.array([7,8,9,10,1,2,3,4,5,6])
findCutline(a)

4

**[Ric wrote]:** With the auxiliary function to find the cutline index I can write the binary search function.

In [176]:
def findElement(arr,e):
    """Input: a rotated numpy array and an element to search, an integer value
    Output: The index of the element in the array"""
    
    def bSearch(arr,e,low,high):
        if high == low:
            if arr[low] == e:
                return low
            else:
                return print("The element is not in the array")
        
        mid = (low+high)//2
        
        if arr[mid] == e:
            return mid
        elif arr[mid] > e:
            if low == mid: # the element is not in the array
                return print("The element is not in the array")
            else:
                return bSearch(arr,e,low,mid-1)
        else:
            return bSearch(arr,e,mid+1,high)
        
    if len(arr) == 0:
        raise ValueError("Cannot search element in an empty array")
    
    indx = findCutline(arr)
    
    if indx == 0: # The array was not rotated after all
        return bSearch(arr,e,0,len(arr)-1)
    
    left = arr[indx:]
    right = arr[:indx]
    
    if e < left[0]:
        return print("The element is not in the array")
    elif e > right[-1]:
        return print("The element is not in the array")
    elif e > left[-1]:
        return bSearch(right,e,0,len(right)-1)
    else:
        try:
            return bSearch(left,e,0,len(left)-1) + indx
        except:
            return None

In [177]:
a = np.array([7,8,9,10,12,1,2,3,5,6])

In [178]:
findElement(a,10)

3

In [179]:
findElement(a,7)

0

In [180]:
findElement(a,9)

2

In [181]:
findElement(a,1)

5

In [182]:
findElement(a,3)

7

In [183]:
findElement(a,6)

9

In [184]:
a[9]

6

In [185]:
# Testing an element not in array smaller than all elements
findElement(a,0)

The element is not in the array


In [186]:
# Testing an element not in rray greater than all elements
findElement(a,662)

The element is not in the array


In [187]:
# Testing a missing element within the left array
findElement(a,4)

The element is not in the array


In [188]:
# Testing amissing element within the right array
findElement(a,11)

The element is not in the array


In [189]:
# Testing ValueError if array is empty
b = []
b = np.array(b)
findElement(b,811)

ValueError: Cannot search element in an empty array

**(2)** Given an array of integers, implement a recursive Python program that finds a
    valley element in O(logn) runtime. Submit both the Python code and a
    screenshot of its results.<br>
    
*Notes:*
1. In an array of integers, a valley element is the one which is less
       than or equal to the adjacent integers.
       For example, in array A = {5, 3, 20, 4, 1, 0}, a valley element is 3.
2. The integer at index 0 is considered to be a valley point, if it is less
       than the integer at index 1.
       For example, in array A = {3, 5, 20, 4, 1, 0}, a valley element is 3.
3. The integer at index n-1 is considered to be a valley point, if it is less
       than the integer at index n-2.
       For example, in array A = {3, 5, 20, 4, 1, 0}, another valley element is 0.

In [211]:
# We need to find a valley not all the valleys
# To find in O(log[n]) time we need to use binary search

def findValleyAux(arr, low, high, n):

    mid = (low + high) // 2

    # Compare middle element with its neighbours (if neighbours exist)
    if ((mid == 0 or arr[mid-1] > arr[mid]) and
            (mid == n-1 or arr[mid+1] > arr[mid])):
        return f"At index '{mid}' valley element <{arr[mid]}> was found"

    # If middle element is not minima and its left neighbour is smaller than it, then left half must have a local minima.
    elif (mid > 0 and arr[mid-1] < arr[mid]):
        return findValleyAux(arr, low, (mid -1), n)

    # If middle element is not minima and its right neighbour is smaller than it, then right half must have a local minima.
    else:
        return findValleyAux(arr, (mid + 1), high, n)


def findValley(arr):
    """Input: An array of unique integers
    Output: Returns the index where a valley element is found and its value
    
    Notes: 1- Assumes the array has no repeated elements
           2- The functions finds a valley element (kind of a minimum value),
           it does not guarantee finding a global minima (the deepest valley in the array)"""
    
    n = len(arr)
    
    if n == 0:
        raise ValueError("Cannot search a valley in an empty list")
    elif n == 1:
        raise ValueError("Cannot search a valley in a list of length equal to 1")
    elif len(set(arr)) != n:
        raise ValueError("The array cannot contain repeated elements")
    else:    
        return findValleyAux(arr, 0, n-1, n)

In [212]:
# Test cases
c = np.array([5,4,1,2,3]) # The valley is exactly n the middle
d = np.array([1,2,3,4,5]) # The valley is on index 0
e = np.array([5,4,3,2,1]) # The valley is on index -1
f = np.array([6,5,4,1,2,3]) # The valey is on the midddle of an even array, part 1
g = np.array([6,5,1,2,3,4]) # The valey is on the midddle of an even array, part 2
h = np.array([10,1,12,13,2,20]) # Multiple valleys in even array
i = np.array([10,1,12,13,2,20,33]) # Multiple valleys in odd array
j = np.array([5,3,20,4,1,0]) # Case provided in question
k = np.array([3,5,20,4,1,0]) # Case provided in question

In [213]:
findValley(c)

"At index '2' valley element <1> was found"

In [214]:
findValley(d)

"At index '0' valley element <1> was found"

In [215]:
findValley(e)

"At index '4' valley element <1> was found"

In [216]:
findValley(f)

"At index '3' valley element <1> was found"

In [217]:
findValley(g)

"At index '2' valley element <1> was found"

In [218]:
findValley(h)

"At index '1' valley element <1> was found"

In [219]:
findValley(i)

"At index '1' valley element <1> was found"

In [220]:
findValley(j)

"At index '1' valley element <3> was found"

In [221]:
findValley(k)

"At index '0' valley element <3> was found"

In [222]:
# Cases to test errors
l = np.array([])
m = np.array([3])

In [223]:
findValley(l)

ValueError: Cannot search a valley in an empty list

In [224]:
findValley(m)

ValueError: Cannot search a valley in a list of length equal to 1

In [225]:
# Cases not covered by the docstring
r = np.array([5,4,1,1,1,2,3])
s = np.array([1,1,2,3])
t = np.array([9,7,6,5,5,5,5])

In [226]:
findValley(r)

ValueError: The array cannot contain repeated elements

In [227]:
findValley(s)

ValueError: The array cannot contain repeated elements

In [228]:
findValley(t)

ValueError: The array cannot contain repeated elements

## -- The homework ends here, disregard the content below --
**-- I wrote the function below thinking the binary search needed to return
either True/False. I did not used when I realized the requirement was different,
however I want to keep it with this material for future use--**

**[Ric wrote]:** Now I am going to define an auxiliar function to de-rotate the array

In [33]:
def derotate(arr):
    """Input: A rotated numpy array
    Output: The de-rotated array"""
    
    indx = findCutline(arr)
    
    if indx == 0: # The array was not rotated
        return arr
    
    array = np.concatenate((arr[indx:], arr[:indx]), axis=None)
    
    return array

In [34]:
derotate(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
b = np.array([1,2,3,4,5,6,7,8])
derotate(b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
c = np.array([2,3,4,5,6,7,8,1])
derotate(c)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
d = np.array([0,1,2,3,4,5,-5,-4,-3,-2,-1])
derotate(d)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])